p = r'C:\Users\chuan\Doubao\chats\2026-09-19\new-chat-1\streamlit_app.py'
c = open(p, encoding='utf-8').read()

# 1. query_between 加 device 参数
c = c.replace(
    'def query_between(start_dt, end_dt):\n    """按时间段查询历史记录"""\n    conn = db_connect()\n    try:\n        with conn.cursor() as cur:\n            cur.execute(\n                f"SELECT id, device_address, illuminance, measure_time "\n                f"FROM {C.TABLE} "\n                f"WHERE measure_time BETWEEN %s AND %s "\n                f"ORDER BY measure_time DESC LIMIT 10000",\n                (start_dt.strftime("%Y-%m-%d %H:%M:%S"),\n                 end_dt.strftime("%Y-%m-%d %H:%M:%S"))\n            )',
    'def query_between(start_dt, end_dt, device=None):\n    """按时间段查询历史记录，可指定传感器"""\n    conn = db_connect()\n    try:\n        where = "measure_time BETWEEN %s AND %s"\n        params = [start_dt.strftime("%Y-%m-%d %H:%M:%S"),\n                  end_dt.strftime("%Y-%m-%d %H:%M:%S")]\n        if device:\n            where += " AND device_address = %s"\n            params.append(device)\n        with conn.cursor() as cur:\n            cur.execute(\n                f"SELECT id, device_address, illuminance, measure_time "\n                f"FROM {C.TABLE} "\n                f"WHERE {where} "\n                f"ORDER BY measure_time DESC LIMIT 10000",\n                params\n            )'
)

# 2. 历史查询 UI 加传感器选择
c = c.replace(
    '    c1, c2, c3, c4 = st.columns([1, 1, 1, 1])\n    today = datetime.now().date()\n    d1 = c1.date_input("起始日期", value=today - timedelta(days=7))\n    d2 = c2.date_input("结束日期", value=today)\n    t1 = c3.time_input("起始时间", value=datetime(2000, 1, 1, 0, 0).time())\n    t2 = c4.time_input("结束时间", value=datetime(2000, 1, 1, 23, 59).time())\n\n    if st.button("🔍 查询历史记录", type="primary"):\n        start_dt = datetime.combine(d1, t1)\n        end_dt = datetime.combine(d2, t2)\n        if start_dt > end_dt:\n            st.error("起始时间不能晚于结束时间")\n        else:\n            st.session_state["query_df"] = query_between(start_dt, end_dt)\n            st.session_state["query_ok"] = True\n            st.session_state["query_range"] = f"{start_dt:%Y-%m-%d %H:%M} ~ {end_dt:%Y-%m-%d %H:%M}"',
    '    c1, c2, c3, c4 = st.columns([1, 1, 1, 1])\n    today = datetime.now().date()\n    d1 = c1.date_input("起始日期", value=today - timedelta(days=7))\n    d2 = c2.date_input("结束日期", value=today)\n    t1 = c3.time_input("起始时间", value=datetime(2000, 1, 1, 0, 0).time())\n    t2 = c4.time_input("结束时间", value=datetime(2000, 1, 1, 23, 59).time())\n    sensor_opt = st.selectbox("传感器", ["全部", "1号(0x01)", "2号(0x02)", "3号(0x03)", "4号(0x04)"])\n    sensor_map = {"全部": None, "1号(0x01)": 1, "2号(0x02)": 2, "3号(0x03)": 3, "4号(0x04)": 4}\n    sel_device = sensor_map[sensor_opt]\n\n    if st.button("🔍 查询历史记录", type="primary"):\n        start_dt = datetime.combine(d1, t1)\n        end_dt = datetime.combine(d2, t2)\n        if start_dt > end_dt:\n            st.error("起始时间不能晚于结束时间")\n        else:\n            st.session_state["query_df"] = query_between(start_dt, end_dt, sel_device)\n            st.session_state["query_ok"] = True\n            dev_label = f"{sensor_opt} · " if sel_device else ""\n            st.session_state["query_range"] = f"{dev_label}{start_dt:%Y-%m-%d %H:%M} ~ {end_dt:%Y-%m-%d %H:%M}"'
)

# 3. 导出加格式选择
c = c.replace(
    '        csv_bytes = qdf.to_csv(index=False).encode("utf-8-sig")\n        xlsx_buf = BytesIO()\n        qdf.to_excel(xlsx_buf, index=False, sheet_name="光照记录")\n        e1, e2 = st.columns(2)\n        e1.download_button(\n            "⬇ 导出 CSV（文本文件）", csv_bytes,\n            file_name=f"光照记录_{d1}_{d2}.csv", mime="text/csv",\n            use_container_width=True)\n        e2.download_button(\n            "⬇ 导出 Excel（电子表格）", xlsx_buf.getvalue(),\n            file_name=f"光照记录_{d1}_{d2}.xlsx",\n            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",\n            use_container_width=True)',
    '        csv_bytes = qdf.to_csv(index=False).encode("utf-8-sig")\n        xlsx_buf = BytesIO()\n        qdf.to_excel(xlsx_buf, index=False, sheet_name="光照记录")\n        e1, e2, e3 = st.columns(3)\n        e1.download_button(\n            "⬇ CSV", csv_bytes,\n            file_name=f"光照记录_{d1}_{d2}.csv", mime="text/csv",\n            use_container_width=True)\n        e2.download_button(\n            "⬇ Excel", xlsx_buf.getvalue(),\n            file_name=f"光照记录_{d1}_{d2}.xlsx",\n            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",\n            use_container_width=True)\n        e3.download_button(\n            "⬇ CSV+Excel(打包)", csv_bytes,\n            file_name=f"光照记录_{d1}_{d2}.csv", mime="text/csv",\n            use_container_width=True,\n            help="同时导出 CSV 和 Excel，分别点上面两个按钮即可")'
)

open(p, 'w', encoding='utf-8').write(c)
print("done")
